package Client.enums;

public enum QueryResponses {
    OK,
    USER_NOT_EXIST,
    PASSWORD_INCORRECT,
    USERNAME_EXIST,
    NICKNAME_EXIST,
    IGNORE,
    RESET_COLOR_ADJUST,
    BLOOM_COLOR_ADJUST,
    FOG,
    REVEALED,
    COMBAT_UNIT_SELECTED,
    NONCOMBAT_UNIT_SELECTED,
    UNIT_NOT_SELECTED,
    SET_TECH_VISIBLE,
    SET_TECH_INVISIBLE

}
